[gpio]
    [[gpio.pumps]]
    relayPin = 4
    sensorPin = 5
    flowLPM = 2
    primeTimeMillis = 500

    [[gpio.pumps]]
    relayPin = 22
    sensorPin = 6
    flowLPM = 2
    primeTimeMillis = 500

[serial]
portName = "/dev/ttyUSB1"
baudRate = 9600
bufferSize = 1000
sensorUpdateMillis = 100

