[[pumps]]
pin = 4
flowLPM = 2
primeTimeMillis = 500

[[pumps]]
pin = 22
flowLPM = 2
primeTimeMillis = 500

# [[pumps]]
# pin = 6
# flow = 2.0
# primeTime = 0.5
# [[pumps]]
# pin = 26
# flow = 2.0
# primeTime = 0.5

