[[pumps]]
pin = 4
flowLPM = 2
primeTimeMillis = 500

[[pumps]]
pin = 22
flowLPM = 2
primeTimeMillis = 500

[serial]
portName = "/dev/ttyUSB1"
baudRate = 9600
bufferSize = 1000

# [[pumps]]
# pin = 6
# flow = 2.0
# primeTime = 0.5
# [[pumps]]
# pin = 26
# flow = 2.0
# primeTime = 0.5

